### ISSUE TITLE
Display c/a as a proper fraction.

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#10]
In the First Law Screen, when you check eccentricity, the panel shows as 'Eccentricity = c / a' but it should show as a vertical fraction.

**Comment by AgustinVallejo** [comment]
To me it looks ok, but not sure about that extra space there. Also tried to fix it for a bit without luck. What's your opinion @DianaTavares?

**Comment by DianaTavares** [comment]
I like it! yeah, it has some extra space, but this sim has the space for that. The fraction looks perfect for me! 

What worriers me is that you can have the Eccentricity panel, even when the "Axes" checkbox is unselected: 
![image](https://user-images.githubusercontent.com/26031501/232921908-b0adc42e-22e1-49e8-9143-2a5e8313ecdf.png)

This is problematic because then is not trivial for users to know how to inactivate the eccentricity. They need to activate again axes and then unselect eccentricity. I find this not very practical. 

If we decide that it is not necessary to have the axes active to see and interact with the Eccentricity, then it doesn't need to be a nested checkbox.

**Comment by AgustinVallejo** [comment]
- [ ] Will unnest eccentricity and change semiaxis to semiaxes
