### ISSUE TITLE
Third Law: Add a pink "out of bounds" arrow when the data point gets big

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#13]
@DianaTavares Could you paste the mockup image here?

**Comment by DianaTavares** [comment]
It is not just the pink arrow, also the graph. The graph will be drawn while the orbit is moving:
![image](https://user-images.githubusercontent.com/26031501/231242955-6a5fe733-2d05-4866-bdd3-184aef06acf8.png)


 and when the dot gets out of the graph view, the pink arrow appears, indicating that it is out of scale:
![image](https://user-images.githubusercontent.com/26031501/231243177-d2de2251-fb02-43da-9434-3f04fd89f4e0.png)


@AgustinVallejo also needs to play with the scale of the graph because he mentioned that is important to analyze this graph for small orbits, and now it is not well visualized.

**Comment by AgustinVallejo** [comment]
Pushed an initial working idea, we should meet to discuss the proper behavior of this arrow, some items to consider:

- [ ] Position within the graph: Should it be on the path, or floating about?
- [ ] Direction: Should it point along the path, or towards the body dot, or just a 45° diagonal direction?
- [ ] Length: Will the position of the body determine the length of this arrow?
