### ISSUE TITLE
Third Law panels resize as subcomponents change

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#151]
... this is still a problem.  It began its life in https://github.com/phetsims/keplers-laws/issues/86, which we closed prematurely.  For meta issue https://github.com/phetsims/keplers-laws/issues/122.

**Comment by pixelzoom** [comment]
Something to try:
* set a maxWidth for ThirdLawAccordionBox EquationNode
* set minWidth and minHeight for ThirdLawAccordionBox

Alternatively we could listen to localeProperty and do something to adjust minWidth and maxWidth for ThirdLawAccordionBox?

**Comment by pixelzoom** [comment]
It looks like `preferredSize` is not being respected when changing string lengths with `?stringTest=dynamic`.   I'm out of ideas. You'll need to consult with @jonathanolson on this one.

**Comment by AgustinVallejo** [comment]
Met with @jonathanolson and we solved this by doing the following:

1. Removing maxWidths from individual texts in the equation, as they were causing inconsistencies in font sizes.
2. Setting align: 'origin' in the equation HBox
3. Replacing the VBox of FractionNode for a simple node, and setting the position of numerator and denominator around the fraction line so that everything was properly vertical aligned.
4. The global equation HBox got a maxWidth of 260 so everything shrinks accordingly if oversized.

**Comment by AgustinVallejo** [comment]
However, the above solution brings up issues of its own: When the equation becomes really long, i.e. with sort of big orbits and displaying T^3, changing the orbit causes immediate responses in the font size, which may or may not look buggy. With @jonathanolson we agreed that this might be the best scenario unless we go for a smaller default font size.

@DianaTavares @arouinfar could you play with the sim and let us know what you think of the text changing sizes so fast? If it's okay, we'll close this final issue and send the sim to QA.
![image](https://github.com/phetsims/keplers-laws/assets/37052186/200007a1-66f6-4f72-8366-01b9efbafe6f)

**Comment by DianaTavares** [comment]
I find it good! It is the best behavior for numbers that can be small and large in the same dragging. Closing and Sim ready for QA!!!
