### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by arouinfar** [phetsims/keplers-laws#193]
@DianaTavares would like to update the screenshots on the website. Unfortunately, we forgot to do this while the sim was in RC, and we will need to publish a maintenance release for the screenshots to update on the website.

@DianaTavares will retake the screenshots and then assign this issue to me to commit them to main and 1.1.

We'll need:
- [x] One screenshot for each screen 
- [x] Use `screens` query parameter to take screen-specific screenshots, to be named `keplers-laws-screenshot-screen1`, etc.

**Comment by DianaTavares** [comment]
![Keplers-laws-screenshot-alt1](https://github.com/phetsims/keplers-laws/assets/26031501/8a611831-bc16-4404-badb-b04e7e85489c)
![Keplers-laws-screenshot-alt2](https://github.com/phetsims/keplers-laws/assets/26031501/c4106f82-d758-4aff-a5f3-0b9290bd64fb)
![Keplers-laws-screenshot-alt3](https://github.com/phetsims/keplers-laws/assets/26031501/f5dd3ec3-6f37-4b6a-af49-ae5f42843adf)
![keplers-laws-screenshot-screen1](https://github.com/phetsims/keplers-laws/assets/26031501/92da33a6-7144-467a-808f-fd6e64152b9e)
![keplers-laws-screenshot-screen2](https://github.com/phetsims/keplers-laws/assets/26031501/603c5ce8-3096-4e7f-8c17-85974c0feba6)
![keplers-laws-screenshot-screen3](https://github.com/phetsims/keplers-laws/assets/26031501/5caefcc1-dd1e-4d89-8c18-9fd0c086305f)
![keplers-laws-screenshot-screen4](https://github.com/phetsims/keplers-laws/assets/26031501/c10b72fc-050a-4405-a0d9-5956617dc192)
![Keplers-laws-screenshot](https://github.com/phetsims/keplers-laws/assets/26031501/82cbd5cd-5764-43d1-9f44-b79d41af50f2)

**Comment by DianaTavares** [comment]
This is the link to the files in [SharePoint](https://o365coloradoedu.sharepoint.com/:f:/r/sites/PHYS-phet-pilot/PhET%20Files/PhET%20Files/PhET%20Sim%20Design/Kepler%27s%20Law%20HTML5/[Assets](https://o365coloradoedu.sharepoint.com/:f:/r/sites/PHYS-phet-pilot/PhET%20Files/PhET%20Files/PhET%20Sim%20Design/Kepler%27s%20Law%20HTML5/Assets?csf=1&web=1&e=KAQBAc)?csf=1&web=1&e=KAQBAc). I call keplers-laws.screenshot to the screenshot of the second screen because I think that the second law is the most famous Kepler law and is better to use that pictures as a representation of this simulation (principal screenshot). Then alt1 is the first screen, alt2 is the third, and alt3 is the four screen

**Comment by arouinfar** [comment]
Thanks @DianaTavares! I noticed the dimensions of the alt2 screenshot were a bit off, so I retook that one. Otherwise, things looked good and I committed the screenshots to main and the 1.1 branch.

@AgustinVallejo as far as I know, the only way to update the screenshots on the website is to publish a maintenance release of Kepler's Laws. While the screenshots have been committed to the release branch (as is standard), I don't believe the website actually uses the active release branch to populate the sim page, and instead looks to main. Please check in with @mattpen as needed.

**Comment by pixelzoom** [comment]
I believe that Kepler's Laws was maintaince released on 10/5/23 with new screenshots.

@AgustinVallejo can this issue be closed?

**Comment by AgustinVallejo** [comment]
Yup, didn't notice this was being discussed here, sorry. Closing!
