### ISSUE TITLE
Client-configurable target orbits

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#210]
In the context of https://github.com/phetsims/keplers-laws/issues/206
Because in `TargetOrbits.ts` we list all the orbits that we reference across the sim, there's a possibility of selecting Eris, Nereid and Halley as target orbits in the studio, but they are not supported by the target orbit combo box, so we end up seeing this:
![image](https://github.com/phetsims/keplers-laws/assets/37052186/c9ee0bb4-5298-44f4-81de-7ca5232fd77c)

![image](https://github.com/phetsims/keplers-laws/assets/37052186/5a100a33-cd08-4193-938a-f289af027717)

**Comment by AgustinVallejo** [comment]
Moreover, when doing this with the dev tools open, it causes the sim to crash.

**Comment by AgustinVallejo** [comment]
In 11/16's meeting, we decided to include these orbits as hidden combobox options, as well as to add the possibility of 2 customizable orbits, like in MSS.

**Comment by AgustinVallejo** [comment]
Added most of the functionality in the above commit. Assigning myself and @pixelzoom to work on implementing something similar to `PhetioOrbitalSystemProperty.ts` in Keplers, so the user can customize the two new orbits.

**Comment by pixelzoom** [comment]
@arouinfar This is ready for your review.   The implementation is similar to what we did for client-configurable presets in My Solar System.  Here's a summary of the new Properties:

Model Properties (in all screens except Second Law):

* `model.phetioTargetOrbits.targetOrbit1Property`
* `model.phetioTargetOrbits.targetOrbit2Property`
* `model.phetioTargetOrbits.targetOrbit3Property`
* `model.phetioTargetOrbits.targetOrbit4Property`

... all of which have this default JSON value:

```json
{
  "eccentricity": 0,
  "semiMajorAxis": 1
}
```

View Properties:

* `targetOrbitComboBox.listBox.targetOrbit1Item`
* `targetOrbitComboBox.listBox.targetOrbit2Item`
* `targetOrbitComboBox.listBox.targetOrbit3Item`
* `targetOrbitComboBox.listBox.targetOrbit4Item`

String Properties:

* `targetOrbit1StringProperty`
* `targetOrbit2StringProperty`
* `targetOrbit3StringProperty`
* `targetOrbit4StringProperty`

**Comment by arouinfar** [comment]
@pixelzoom @AgustinVallejo the tree structure and workflow in Studio are working well, but `targetOrbit*Property` does not appear to be stateful. I suspect it's related to the fact that the orbital path isn't stateful, either.

Example case:
1. Set `targetOrbitComboBox.listBox.targetOrbit1Item.visibleProperty` to `true` and select it from the ComboBox.
2. Edit `targetOrbit1StringProperty` to give it a custom name.
3. Edit `model.phetioTargetOrbits.targetOrbit1Property` so that the values are noticeably different from the default.
4. Press "Test" to create a Standard PhET-iO Wrapper. The selected target orbit and the `StringProperty` are correctly restored, but the target orbit retains its default values (eccentricity = 0, semi-major axis = 1).

Also note that the orbital path is not stateful, either. Testing the standard wrapper will display the default path, not the path associated with body 2's current position/velocity. For example:

1. Create a path distinctly different from the default, such as:
![image](https://github.com/phetsims/keplers-laws/assets/8419308/0370647f-2475-47c0-819a-5928e5fdffef)
2. Press Test. Body 2's position and velocity are correct, but the path appears to still be the default.
![image](https://github.com/phetsims/keplers-laws/assets/8419308/0eb21abe-80cf-4144-8492-9c1d7c596497)

**Comment by AgustinVallejo** [comment]
The path part is due to https://github.com/phetsims/keplers-laws/issues/213, I'm looking into it.

**Comment by pixelzoom** [comment]
@arouinfar said:
> ... `targetOrbit*Property` does not appear to be stateful.

Since we used the same approach for `orbitalSystem*Property` in MSS, we should verify that MSS does not have the same problem.

**Comment by pixelzoom** [comment]
I see the problem with `targetOrbit*Property`.    Let me describe it in terms of `targetOrbit1Property`.   We have 3 instances of `targetOrbit1Property`, for the _First Law_, _Second Law_, and _All Laws_ screens.   So changing only 1 of those instances results in the other 2 instances resetting `TargetOrbit.TARGET_ORBIT_1` back to its original default values.   So `targetOrbit*Property` needs to be global (`static`?), so that there's 1 instance of each Property for the entire sim.

**Comment by pixelzoom** [comment]
Fix for `targetOrbit*Property` pushed in the above commit.  Instead of an instance of `targetOrbit*Property` per screen, there is now 1 global instance of each.   This is necessary because these Properties are modifying the TargetOrbit enumeration values, which are themselves global.   Here's the Studio tree for these Properties:

<img width="284" alt="screenshot_2909" src="https://github.com/phetsims/keplers-laws/assets/3046552/f44c3ed3-c4e7-4d46-9ea9-24488b367c94">

@AgustinVallejo please review my changes, let me know if you have questions. When you've fixed the statefulness of the orbital path, assign back to @arouinfar for review.

**Comment by AgustinVallejo** [comment]
The path of the orbit should now be updating properly. It was fixed in https://github.com/phetsims/keplers-laws/issues/213 in case any comments need to be done about it.

Returning this one back to @arouinfar for review.

**Comment by arouinfar** [comment]
Looks good in main, thanks @pixelzoom @AgustinVallejo! Closing.
