### ISSUE TITLE
PhET-iO Tree Review 

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#220]
Meta issue for the tree review, below are some relevant issues. Feel free to use them or comment on this one:
- #201
- #206 
- #207 
- #208 
- #209

**Comment by arouinfar** [comment]
I've completed a preliminary review of the tree, and found several issues. I apologize for not being able to write up issues. Please let me know if you need any clarification @pixelzoom @AgustinVallejo.

* `gravityForceScalePowerProperty`
  * Why is this read-only? Does it need to be? It seems like something that clients may want to control with the API since it is tied to the Zoom slider.

* `model.orbitalProperties`
  * Everything here needs units (except for eccentricity, which is dimensionless)

* `model.orbitalAreas.orbitalArea*.sweptAreaProperty`
  * `phetioDocumentation` indicates that this is for internal use only, but this seems like data the client may want to extract. Consider revising `phetioDocumentation`.

* `model.orbitalProperties`
  * Consider renaming to `orbitalData`. “Data” is a friendlier term, and may help clients better find what they are looking for. It’s also a nice complement to the `moreOrbitalData`.

* BUG: Nested “String” and “Semiaxes” checkboxes stay checked when the parent is unchecked. This behavior diverges from the published version of the sim. 

* `topRightPanels`
  * Can we rename this to something like `controlPanels`? `topRight` is a bit strange because not all of its children are on top. If `controlPanels` is unacceptable, perhaps just `rightPanels`.

* `stopwatchNode`
  * Seems buggy to allow clients to change the visibility of the buttons. Do their visibleProperties need to be instrumented?
  * `resetButton.enabledProperty` should be read-only 

* `periodTimerNode`
  * Hiding play button is problematic, much like in `stopwatchNode`.

* Add top-level visibleProperty to all of these.
  * `view.panels.secondLawPanels.periodDivisionsPanel`
  * `view.panels.secondLawPanels.sweptAreaAccordionBox`
  * `view.panels.thirdLawPanels.graphAccordionBox`

* `view.panels.thirdLawPanels.graphAccordionBox.graphNode.visibleProperty`
  * Hiding the `graphNode` looks buggy. Does this need to be instrumented?

* `view.panels.thirdLawPanels.graphAccordionBox.graphNode.*VisitedAxisProperty`
  * Should this be read-only? Seems buggy otherwise.

**Comment by AgustinVallejo** [comment]
@arouinfar thanks for the quick feedback! Also, it seems the `gravityForceScalePowerProperty` also affects MSS, should we apply this change before publishing the newest version? Currently in https://github.com/phetsims/qa/issues/1015

**Comment by pixelzoom** [comment]
`gravityForceScalePowerProperty` is readonly because the simulation sets it.  In LabModel:

```ts
        if ( orbitalSystem === OrbitalSystem.FOUR_STAR_BALLET ) {
          this.gravityForceScalePowerProperty.value = -1.1;
        }
```

We could make it readonly for the Intro screen only, writeable for the Lab screen and all screens in Kepler's Laws.  But we're going to need to discuss this with @arouinfar.  So I recommend that we make no changes to `gravityForceScalePowerProperty` for now, and proceed with MSS 1.3 RC testing.

**Comment by pixelzoom** [comment]
@AgustinVallejo FYI... I converted https://github.com/phetsims/keplers-laws/issues/220#issuecomment-1848255207 to a checklist, and moved the "BUG" to https://github.com/phetsims/keplers-laws/issues/221.

**Comment by AgustinVallejo** [comment]
For the `stopwatchNode` comment we will defer them since it's common code and it needs a PhET-iO design. @pixelzoom created the issue https://github.com/phetsims/scenery-phet/issues/827 for that

**Comment by pixelzoom** [comment]
@AgustinVallejo and I paired on this.  We were able to satisfy all requests. Back to @arouinfar for review, close if OK.

Note that the subtree for `stopwatchNode` now looks as shown below.  And we uninstrumented `enabledProperty` for both buttons.

<img width="234" alt="screenshot_2929" src="https://github.com/phetsims/keplers-laws/assets/3046552/66721592-c4ea-47b7-a117-b0037541ef13">

**Comment by arouinfar** [comment]
Thanks @AgustinVallejo @pixelzoom. All of the changes look good on main. My initial review was a bit rushed, so I am in the process of completing a second, more thorough review. I hope to have it wrapped up today, and it will include specifying updates to `phetioFeatured` over in #217.

**Comment by arouinfar** [comment]
I completed the tree review, and found a few more issues. Since these seem relatively minor, I'll use a checklist.

- [ ] `model.periodTracker`: Everything collected here looks like implementation details to me. Let's add `phetioDocumentation` to each child that says, "For internal use only."
- [ ] `massNumberControl.visibleProperty`: Uninstrument this. Clients should use the parent's `visibleProperty` instead.
- [ ] Add a link to `model.bodies.sun.massProperty` under `view.panels.thirdLawPanels.starMassPanel.massNumberControl`

**Comment by pixelzoom** [comment]
@AgustinVallejo let me know if you need any assistance with this.

**Comment by AgustinVallejo** [comment]
Ready for re-review @arouinfar. Please note that the second commit is wrong since I misread the assignment, but it's fixed on the next one.

**Comment by arouinfar** [comment]
Thanks @AgustinVallejo! The changes all look good in main, closing.
