### ISSUE TITLE
Period divisions graph appearing in reverse order

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#233]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Safari 17.1.2

**Problem description**
For https://github.com/phetsims/qa/issues/1023, on the Second Law Screen, the graph is getting filled in the opposite direction, 4 --> 3 --> 2 --> 1 instead of 1-2-3-4.

**Steps to reproduce**
1. On the Second Law Screen, Press play and watch the graph. 

**Visuals**

https://github.com/phetsims/keplers-laws/assets/87318828/d40812e6-2e6e-4e3f-81ee-1d140e0742bf

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Kepler's Laws‬
URL: https://phet-dev.colorado.edu/html/keplers-laws/1.2.0-dev.7/phet/keplers-laws_all_phet.html
Version: 1.2.0-dev.7 2024-01-09 17:06:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.2 Safari/605.1.15
Language: en-US
Window: 1357x684
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by arouinfar** [comment]
This change was necessary for the index for the swept area in the PhET-iO tree to match up with the index used in the graph. I think the commits were made in #214 but the discussion around reversing the order doesn't appear to have made it onto GitHub. 

I'm not thrilled about this change, but there didn't appear to be any other way to get the `phetioID` to sync up correctly with the view. 

@AgustinVallejo please correct me if I'm wrong. Otherwise, this issue can be closed as wont-fix.

**Comment by AgustinVallejo** [comment]
You're right, this was decided on, I'm going to close this issue and summarize our slack discussion in the one you linked.
