### ISSUE TITLE
My reviews of the 1.0.2 dev version of Kepler 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#25]
Hi! I interact with [this version](https://phet-dev.colorado.edu/html/keplers-laws/1.0.0-dev.1/phet/keplers-laws_all_phet.html) and these are my comments:

- [x] Do we need a rewind button?  I don't see it importance.
- [x] for big orbits, it is easy to lose the planet. Do we require a “return body” option? In that case, how it should work? 
- [x] We require the text of “forces vectors are too small to display”
- [x] new icons for the screens?
- [x] Period timer

**Comment by AgustinVallejo** [comment]
Design decision on 25/05:
1. Yes, let's keep the rewind button.
2. Because we're keeping the rewind button, there's no need for a return bodies button. Also we'll pause the sim when mass is changed to avoid sending the body in an escape trajectory. If the body goes offscreen, it's always temporarily, and you can always rewind to a proper state.
3. No need for a small vector message.
4. Done!
5. Tracked in https://github.com/phetsims/keplers-laws/issues/12
