### ISSUE TITLE
Interaction between the always circular button and disabling planet interaction

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/keplers-laws#258]
**Device**
Samsung
**OS**
Win 11
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/1034
I noticed some odd interactions in studio between the feature disabling planet interaction and the always circular button. These aren't necessarily bugs, but it might be worth including in the "Disable interaction with the planet" section of the examples document. If you disable velocity control, then turn the always circular check on and off, interaction with the velocity control will be available again. If you turn velocity control on when always circular is checked you can't actually take control and the hum sound turns on when trying to take control.

**Comment by Nancy-Salpepi** [comment]
This is definitely an issue because it happens in the Standard wrapper. 
1. In studio on any screen, set `planetVelocityVectorNode.inputEnabledProperty` to false. 
2. Press Test
3. Go to the screen you made the change on and check Always Circular and then uncheck it --the velocity vector is now movable. 

https://github.com/phetsims/keplers-laws/assets/87318828/2537dc30-f9a2-47b5-bc27-63fbe8a6cadc

**Comment by AgustinVallejo** [comment]
Addressed in the above commit, please review and mark as cherry pick ready, if done.

**Comment by KatieWoe** [comment]
The velocity control still comes back after turning off always circular. The second problem of turning on control while always circular is still on does seem to be fixed.

**Comment by KatieWoe** [comment]
Looks ok on main

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.2
Closing!
