### ISSUE TITLE
All PatternStringProperties should be instrumented

### ISSUE THREAD

**Issue by zepumph** [phetsims/keplers-laws#42]
From https://github.com/phetsims/phet-io/issues/1942, I passed some tandems through but mostly `Tandem.OPT_OUT`s, please review this sim's instrumentation of PatternStringProperties in correlation to this sims' phet-io priorities.  In general all PatternStringProperties should be instrumented unless they are just symbols or patterns that aren't for i18n purposes.

**Comment by pixelzoom** [comment]
Two things related to this issue:

1. It is no longer necessary to instrument all instances of PatternStringProperty.  They will be instrumented only when requested by the designer.  And since this sim does not currently support PhET-iO, that decision is deferred to the future.

2. PatternStringProperty no longer requires a tandem.  So in https://github.com/phetsims/keplers-laws/commit/0b4c1536d1c0b1e4a383f6ddfefabbbdf3659b67, I removed the Tandem.OPT_OUT that @zepumph had added.

@AgustinVallejo let me know if you have questions. Close if OK.
