### ISSUE TITLE
Convert WAV to MP3?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#96]
For code review #83 ...

Why is WAV format being used for some of the files in keplers-laws/sound/?  WAV format is much larger that MP3.  Should WAV files be converted to MP3?

WAV files are used in OrbitalSound.ts:

```tw
// import saturatedSineLoopTrimmed_wav from '../../../sounds/saturatedSineLoopTrimmed_wav.js';
// import charges_wav from '../../../sounds/charges_wav.js';
import OrbitEccentricity_loop_v2_wav from '../../../sounds/OrbitEccentricity_loop_v2_wav.js';
```

It would be good to have @jbphet chime in here too.

**Comment by jbphet** [comment]
Generally using MP3 files are preferred due to their smaller size.  There are some cases where WAV files are needed because the MP3 files don't loop well due to their tendency to always have a bit of silence at the beginning of them once they are encoded which, in my experience, is difficult to remove.  If the current WAV files are being used as loops, my suggestion would be to try encoding them as MP3 files and testing them in the sim on multiple browsers.  If you don't hear any glitches in the loops you should be good to go.  If you do, use the WAV file.

If these WAV files are _not_ being used as loops they should definitely be compressed into MP3 files.

For more information on how to encode audio for our sims, please see https://github.com/phetsims/tambo/blob/main/doc/encoding-audio.md.

**Comment by AgustinVallejo** [comment]
The WAV files are being used as loops and @Ashton-Morris recommended to keep them as WAV because of the reason mentioned by @jbphet. So keeping the file this way and closing.

**Comment by pixelzoom** [comment]
Didn't @jbphet recommend trying the loop as MP3, to see if it glitches?  Did you try that?

**Comment by Ashton-Morris** [comment]
@AgustinVallejo I have added an .[mp3 version](https://o365coloradoedu.sharepoint.com/:u:/s/PHYS-phet-pilot/EQbNq_u3bDtDr32L_YfamHABtzZyG-itkH6qMejGmTpDXA?e=bFs7Qn) if you want to try JB's looping trick.
